services:
  database:
    image: postgres:16
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tagproducts_database
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data

  tagproducts_backend:
    build: backend/
    container_name: tagproducts_backend
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - backend/.env
    depends_on:
      - database
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma db push &&
        npm run dev
      "

  tagproducts_frontend:
    depends_on:
      - tagproducts_backend
    build: frontend/
    container_name: tagproducts_frontend
    restart: always
    ports:
      - "3000:3000"

volumes:
  database_data: